### ISSUE TITLE
Generate sub-page for each function

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basiljs.github.io#1]
As mentioned by @trych in https://github.com/basiljs/basil.js/issues/131

**Comment by fabianmoronzirfas** [comment]
Hm not 131but https://github.com/basiljs/basil.js/pull/169

**Comment by fabianmoronzirfas** [comment]
I suggest the following file structure:  

    .
    ├── data
    │   ├── endsWith.md
    │   └── startsWith.md
    ├── document
    │   ├── something-else.md
    │   └── another-function.md
    ├── environment
    │   ├── something-else.md
    │   └── another-function.md

So we create one page per every function in a folder of the category. This should be a one time only thing. Then we will have to write proper Markdown files with some more explanation

**Comment by trych** [comment]
Sounds good!
