### ISSUE TITLE
Long descriptions get cut off

### ISSUE THREAD

**Issue by trych** [basiljs/basiljs.github.io#12]
I just noticed this with the new `b.arrange()` function.

The source code is written in one long line:

```js
/**
 * Arranges a page item or a layer before or behind other page items or layers. If using the constants <code>b.FORWARD</code> or <code>b.BACKWARD</code> the object is sent forward or back one step. The constants <code>b.FRONT</code> or <code>b.BACK</code> send the object to the very front or very back. Using <code>b.FRONT</code> or <code>b.BACK</code> together with the optional reference object, sends the object in front or behind this reference object.
 *
 * @cat Document
```

It renders like this:

![bildschirmfoto 2017-12-06 um 11 32 59](https://user-images.githubusercontent.com/9803905/33657330-41286e7c-da79-11e7-9137-1531267d5498.png)

Now, I realize my lack of line breaks is causing the trouble, the question however is, could it not be coded in a way that allows long lines and does not cut them off, but just creates a regular paragraph that automatically breaks at the right edge?

That would be much easier to work with. Or is the problem caused by something different altogether?

**Comment by fabianmoronzirfas** [comment]
It is not that the long line gets cut of. Its the html in the description. 
> If you want to use HTML for highlighting something in your description or to add a link use the @description or @desc tags. This also allows to place your description anywhere in the comment block.  
https://github.com/basiljs/basil.js/wiki/Writing-Documentation#descriptions

**Comment by fabianmoronzirfas** [comment]
Added a sentence or two to the wiki about that. 😉

**Comment by trych** [comment]
Argh, I actually remember that now. Sorry, my bad. 😉
