### ISSUE TITLE
Styling: Reference Fit gabs of description

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basiljs.github.io#125]
> Would also be nice to fit the gaps to the height of the descriptions, so in the part where I have two one-line-only descriptions, the gap should be smaller accordingly (I know this probably requires some restructuring of the markdown... )

related to #120 

@trych I don't get this one?

**Comment by fabianmoronzirfas** [comment]
![20190716-151722_Screenshot_Firefox](https://user-images.githubusercontent.com/315106/62265130-335b7e80-b423-11e9-8ebc-75e1938381c9.png)

**Comment by trych** [comment]
Currently there are gaps of different size between the rows. See this image, the red gap is larger than the blue one:

![gaps02](https://user-images.githubusercontent.com/9803905/62275514-65300d80-b442-11e9-8273-69d1f88822c5.jpg)

Ideally the layout should look like this instead with gaps of the same size between all the rows:

![gap03](https://user-images.githubusercontent.com/9803905/62275529-75e08380-b442-11e9-9b6d-3bd584ea0b83.jpg)

**Comment by fabianmoronzirfas** [comment]
Ah. Okay. Now I get it.

**Comment by fabianmoronzirfas** [comment]
This is fixed
