### ISSUE TITLE
Examples are live (please ask questions)

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basiljs.github.io#13]
@ffd8 @trych 
Please ask me questions if you don't understand the structure.  

- https://github.com/basiljs/basiljs.github.io/tree/develop/gallery
- https://github.com/basiljs/basiljs.github.io/tree/develop/tutorials

In the Tutorials example I added some jekyll/html/markdown mixture to see what you can do. You can keep it as straight markdown.  

On the gallery we have a special layout that follows these condiitons:

- if there is an image called index.png (within the images folder and in the list in the yaml fonrtmatter) it will be displayed first.
- if there is a file called index.js it will be included below the text
- if there are other files in the list and in the images folder they will be added below the text

Of course we can change this structure. Also you can include other images as well with a markdown link if you don't add them into the list of files in the frontmatter.

![127 0 0 1_4000_gallery_example_](https://user-images.githubusercontent.com/315106/37518898-677301d6-2917-11e8-8cdb-dec874351aef.png)

**Comment by trych** [comment]
I think a project page should also have buttons to jump to next and previous project. Could you include that?

Otherwise you jump into a project and have to jump back out of it to the overview page again, just to get to the next project.

**Comment by trych** [comment]
And a general question: Is this flexible for the page to be "redesigned".

What I mean: If the frontweb dev layouts the page and decides to go with a slideshow of images instead of all images underneath each other, then all the jekyll and generation stuff should still work, right?

**Comment by fabianmoronzirfas** [comment]
well I would need to do some restructuring of the jekyll code. But yes I can generate HTML lists which can be used as slideshow or what not.

**Comment by trych** [comment]
Ok, cool!

**Comment by fabianmoronzirfas** [comment]
Hey guys. This is the Markdown parser Jekyll is going to use. If you need to look up some feature or are unsure take a look into the quick reference https://kramdown.gettalong.org/quickref.html
