### ISSUE TITLE
Tutorials, no .js + .jsx files needed?

### ISSUE THREAD

**Issue by ffd8** [basiljs/basiljs.github.io#15]
Just curious about the suggested tutorials example.. includes a separate source.jsx file.. I'm guessing the tut's should work with just markdown and inline ```code``` tags? since all the code is spread out throughout the tut rather than at the bottom.

**Comment by trych** [comment]
Yes, I would say tutorials on the website only include inline code, as they do currently.

**Comment by fabianmoronzirfas** [comment]
It was just a suggestion. Can be both
