### ISSUE TITLE
should Gemfile.lock be ignored?

### ISSUE THREAD

**Issue by ffd8** [basiljs/basiljs.github.io#157]
Just went through the update process (now using rvm to avoid using sudo w/ gem) – and perhaps my ruby went a step further than required by this package (2.6.3p62 - latest stable release) – but just realized, it probably doesn't make sense for my changes to also adjust that file (happened after `bundler update`)... so should it be added to an ignore of git settings?

**Comment by ffd8** [comment]
Same goes for package-lock.json?

**Comment by fabianmoronzirfas** [comment]
Actually not. For ruby we can pin the version using `.ruby-version` file and I'm totally into version pinning these days.

**Comment by ffd8** [comment]
Just did some research after having another package-lock.json issue and realized I should be running `npm ci` instead of `npm install`. All good now.
