### ISSUE TITLE
Way to preview references from basil.js repo inline jsdoc?

### ISSUE THREAD

**Issue by ffd8** [basiljs/basiljs.github.io#165]
Not sure if this issue should be on website or main basil.js repo – but is there way we can preview the inline jsdoc nicely as a website just to make sure additions are being formated correctly? I have a feeling the [wiki for API documentation](https://github.com/basiljs/basil.js/wiki#api-documentation) is outdated for current workflow? Would be really helpful to have a basic (not so fancy styled like on website) way of previewing whether it's being parsed right, while writing it.

**Comment by fabianmoronzirfas** [comment]
> I have a feeling the wiki for API documentation is outdated for current workflow?

Totally outdated.

**Comment by fabianmoronzirfas** [comment]
@ffd8 check out the PR on the main repo.
Having the preview in this repo would create overhead.
