### ISSUE TITLE
Updating docs throws errors

### ISSUE THREAD

**Issue by trych** [basiljs/basiljs.github.io#17]
If I run the `npm run build` command to rebuild the docs in the master branch, it now throws this error. Did anything change to cause this error, or did I somehow mess up my system? Is this maybe related to our removal of `b.`?

```
trych13$ npm run build

> basiljs.github.io@0.1.0 build /Users/trych/Documents/basiljs_github_io
> npm run update ; npm run generator


> basiljs.github.io@0.1.0 update /Users/trych/Documents/basiljs_github_io
> npm run pull-latest-basil ; npm run generate-json


> basiljs.github.io@0.1.0 pull-latest-basil /Users/trych/Documents/basiljs_github_io
> npm install basiljs/basil.js#develop -D

+ basiljs@1.1.0
updated 1 package in 1.545s

> basiljs.github.io@0.1.0 generate-json /Users/trych/Documents/basiljs_github_io
> documentation build ./node_modules/basiljs/basil.js -o ./.bin/api/data.json

sh: documentation: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! basiljs.github.io@0.1.0 generate-json: `documentation build ./node_modules/basiljs/basil.js -o ./.bin/api/data.json`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the basiljs.github.io@0.1.0 generate-json script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trych/.npm/_logs/2018-03-22T17_13_35_377Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! basiljs.github.io@0.1.0 update: `npm run pull-latest-basil ; npm run generate-json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the basiljs.github.io@0.1.0 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trych/.npm/_logs/2018-03-22T17_13_35_393Z-debug.log

> basiljs.github.io@0.1.0 generator /Users/trych/Documents/basiljs_github_io
> node .bin/index
```

**Comment by fabianmoronzirfas** [comment]
No. I had this wired error as well. Can you:

- Update to the latest state in branch develop
- remove your node_modules folder
- run `npm install` again
- report back

**Comment by trych** [comment]
Ok, the build works now.
However, when I build on the develop branch it correctly builds the docs for the develop branch of basil, but when I build on the master branch then it does *not* build the docs for the develop branch (but for the master branch instead? I am not sure)

Is that intentional/expected? In the past I would always build on the master branch and then it creates docs from basils current develop branch, that's why I am asking.

**Comment by trych** [comment]
Or I guess, my question would be: Can the build of the development branch that I just did be viewed online anywhere? [basiljs.github.io](https://basiljs.github.io/) still gives me the old docs (with b).

**Comment by fabianmoronzirfas** [comment]
> Or I guess, my question would be: Can the build of the development branch that I just did be viewed online anywhere? basiljs.github.io still gives me the old docs (with b).  

If we merge the develop into master it will show the current state of development on [basiljs.github.io](https://basiljs.github.io)

**Comment by trych** [comment]
Ok, but is there a place to have a look at the rendered output of the develop branch locally? The reference file specifically? If we write inline documentation, I always find it helpful to be able to see the rendered output afterwards.
