### ISSUE TITLE
I am still unable to preview current documentation

### ISSUE THREAD

**Issue by trych** [basiljs/basiljs.github.io#18]
Sorry, this issue is still unresolved for me.

When we work in the `basiljs/basil.js` `develop` branch, we need to be able somehow to preview the documentation that is autobuild via the `npm run build` command.

Currently when I use this command, what seems to happen is that it pulls the inline documentation from the `basiljs/basil.js` master (!) branch and I can only preview the "old" docs, which does not help me at all.

Is there a way to point this process at the develop branch instead, so it builds the docs from the develop branch inline documentation instead? I need to write documentation, and be able to check it, once I merge to the develop branch.

**Comment by trych** [comment]
That would be good, I'm super confused. 🗡 Will write you an email.

**Comment by trych** [comment]
@fabianmoronzirfas Sorry, I *still* don't get this to fully work. Getting quite frustrated here. 😞 The part that does not work this time around is the thing you explained me, where I change the branch to pull from ( https://github.com/basiljs/basiljs.github.io/blob/master/package.json#L9 ). I changed this line to

```
    "pull-latest-basil": "npm install basiljs/basil.js#jsdocstest -D",
```

which somehow automatically changes line 29 as well. But it *still* pulls the develop branch somehow.

Here are the steps I took:

- change line 9 as shown above
- delete all directories (except index.html) in `root/reference` (just to be sure)
- run `npm run build`

After that it already has the incorrect `.md` files (incorrect because they mirror the develop branch) in the `root/reference` folder. So, if I do

- bundle exec jekyll serve

afterwards, it does of course also serve me the incorrect docs. Any ideas how I can pull another branch, *not* the develop branch?

Thanks.

**Comment by fabianmoronzirfas** [comment]
That way worked for me. Try the sha of the commit or change the line to 

    git+ssh://(ADD THE GIT SSH URL HERE)#(ADD BRANCH OR SHA HERR)

**Comment by trych** [comment]
This is crazy. I tried the sha, it still does not work.
It does not give me an error, it will build something, but that something reflects the `develop` branch, not the branch I am referring to. I tried putting a fictional branch `banana` in there, then it actually *does* give me an error in the console, so I am even positive that it catches the branches.

The one thing I have not tested yet is putting the new line in as you suggested. Which line doe I need to change? Line 9? So would it look like this then:

```
    "pull-latest-basil": "npm install git+ssh://(ADD THE GIT SSH URL HERE)#(ADD BRANCH OR SHA HERR) -D"
```

Is that correct?

Fabian, could you please quickly test for me if it actually puts the new description texts in the reference .md files it creates for you? Could you build this thing, pulling from the branch `jsdocstest`, then go into `root/reference/color/noStroke.md` and check, what it says at the description entry? If it works, it *should* start with my test sentence `This has some new text as well.` (compare to the [source](https://github.com/basiljs/basil.js/blob/jsdocstest/src/includes/color.js#L113)).

For me, it only starts like the `develop` source: `Disables drawing the stroke.` 😞

**Comment by fabianmoronzirfas** [comment]
I look into this tonight

**Comment by trych** [comment]
Thanks, that would be great, once this is figured out I could start applying the new categories.

Btw. I just tried the whole process on another system, freshly cloned the repo and set up everything, yet it *still* gives me the wrong result.

**Comment by trych** [comment]
@fabianmoronzirfas If you don't find any time for this now, or if we can't solve it, I could also just do a tiny merge into the develop branch to test if markdown works and then undo that merge. That way I could find out if it works and then continue with the reordering.

**Comment by trych** [comment]
O

**Comment by trych** [comment]
G

**Comment by trych** [comment]
...

**Comment by fabianmoronzirfas** [comment]
Jepp. Tested it. If I change some stuff manually in the bundle and don't run the update command I get that in the output.

**Comment by fabianmoronzirfas** [comment]
hehe. It says that in the npm scripts but I didn't think of this either

**Comment by trych** [comment]
😆 
Ok, I'm quickly off, to find the nearest hole in the floor to disappear into... What the heck did I just do? Hahaha.

**Comment by trych** [comment]
I was reading your comment and was like "'bundle the basil.js file', what does he mean, how would I do that?" Then it hit me. Slowly but hard. Hahahaha.

Thanks @fabianmoronzirfas Sorry for the major confusion, glad that you figured out the obvious. 🤣

**Comment by fabianmoronzirfas** [comment]
pew at least one problem solved tonight. Now to the mysteriously image disappearing on http://hausbrandenburg.net/ any idea why the src of the images is unknown?  
![bildschirmfoto 2018-04-09 um 07 04 24](https://user-images.githubusercontent.com/315106/38518415-19288904-3c3d-11e8-93fb-ace8cfd5b855.png)

**Comment by trych** [comment]
You are definitively asking the wrong person here. 😆
