### ISSUE TITLE
Who is the author?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basiljs.github.io#2]
Hey Super-Basil-Friends,

who is the author for this animation? is it you @b-g ? https://interface.fh-potsdam.de/gestalten-in-code/repeat/basiljs-logo/ 

![out](https://cloud.githubusercontent.com/assets/315106/22964818/c5ce5c9c-f35a-11e6-8cf4-8ef2287e2d6c.gif)

**Comment by b-g** [comment]
Nope! The beauty was created by @ffd8 ! What's the matter?

**Comment by fabianmoronzirfas** [comment]
No matter. I have it sometime in my examples for teaching and never had a proper author for it. :-)
