### ISSUE TITLE
Did the docs/reference updating workflow changed?

### ISSUE THREAD

**Issue by ffd8** [basiljs/basiljs.github.io#219]
@fabianmoronzirfas – was just trying to update the References documentation following the instructions on main readme (although using Master repo as recently suggested, not develop) - but get the following error when trying to commit (it's also changing the package-lock.json file):

```
husky > pre-commit (node v13.13.0)
On branch chore/update-docs
Changes not staged for commit:
	modified:   _source/_data/categories.json
	modified:   _source/_data/cats-and-subcats.json
	modified:   _source/_data/function-list.json
	modified:   _source/download/changelog.txt
	modified:   build-scripts/api/data.json
	modified:   package-lock.json

Untracked files:
	_source/reference/shape/pathToPoints.md
	_source/reference/typography/createOutlines.md

no changes added to commit
```

I've seen you working on this the past weeks.. did the workflow for updating docs change? Thanks in advance for updating the main readme to the current process.

**Comment by fabianmoronzirfas** [comment]
You actually don't need to run the update on the docs manually. The build process clones the latest version by itself and builds the docs. You just need to trigger a rebuild. A small change is enough. Maybe add a html comment into the index.html with a date or something like that. `<!-- trigger rebuild 2020-05-21  -->` I'll need to update the docs a lot. Sorry for that.
