### ISSUE TITLE
Menu should be available on all pages (add to default)

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basiljs.github.io#22]

**Comment by fabianmoronzirfas** [comment]
ul
  li
  li
  li

???

**Comment by fabianmoronzirfas** [comment]
@kajetansom Can you make a suggestion for the markup you want

**Comment by fabianmoronzirfas** [comment]
- [ ] a navigation container including the list. 
- [ ] active class (or something similar) to highlight the active page in the list.
- [ ] an aside or something for this stuff:
- [ ] footer -> div.impressum  // in the footer
- [ ] add the actual page as a class on the body element too for option to be able to change things only on one page. -> body.about

```
aside(id:left)
div.logo
div.nav-o-meter  --> for mobile hamburger
nav.main-menu
ul
li.active a
li a
li a
div.tweet
div.links
main
wrapppper
```

**Comment by fabianmoronzirfas** [comment]
@kajetansom See --> https://github.com/basiljs/basiljs.github.io/blob/feature/menu/_includes/aside-left.html

**Comment by fabianmoronzirfas** [comment]
footer --> https://github.com/basiljs/basiljs.github.io/blob/feature/menu/_includes/footer.html

**Comment by fabianmoronzirfas** [comment]
body --> https://github.com/basiljs/basiljs.github.io/blob/feature/menu/_layouts/default.html#L24

**Comment by kajetansom** [comment]
@fabianmoronzirfas looks good, will let you know if i need something else.

**Comment by fabianmoronzirfas** [comment]
Top

**Comment by fabianmoronzirfas** [comment]
@kajetansom you can update your develop branch
