### ISSUE TITLE
Twitter Feed and Link on the Left

### ISSUE THREAD

**Issue by kajetansom** [basiljs/basiljs.github.io#29]
Please insert it after the navigation inside a div with a meaningful class name

**Comment by fabianmoronzirfas** [comment]
This is a problem. We can't access the twitter API without authentification, but this is hard with only frontend code. @basiljs/basil-js-core-members Any ideas or do we need the feed on the side?

**Comment by fabianmoronzirfas** [comment]
I also thought about setting something up with IFTTT or have somewhere an little node app running that does the auth. (On some Heroku or Zeit free account) The RSS service seems nice **BUT**:  

> Das sogenannte „Scraping” der Dienste ist ohne vorherige Genehmigung von Twitter ausdrücklich untersagt),  
- https://twitter.com/de/tos 

So this might be shut down at some random point.

**Comment by b-g** [comment]
True ... but this might take a long time :)

**Comment by fabianmoronzirfas** [comment]
Yeah. That's right. I'll take a look into both. If I can build something future proof I go for that.

**Comment by b-g** [comment]
BTW. We have been using https://github.com/j7mbo/twitter-api-php with the http://www.generative-gestaltung.de/1/ site ...  to pull the twitter feed for years now (without any maintenance).

**Comment by fabianmoronzirfas** [comment]
Created a micro-service on https://basiljs-latest-tweets.now.sh/ 
See the source here https://basiljs-latest-tweets.now.sh/_src Would be cool to have a repo here on the basil account for the source. @b-g do you have admin rights? Could you create one where I have upload this stuff?

**Comment by fabianmoronzirfas** [comment]
I would go for `latest-tweets` the basiljs in the repo name is redundant. IMHO

**Comment by b-g** [comment]
Done: https://github.com/basiljs/latest-tweets

**Comment by fabianmoronzirfas** [comment]
closed by #37
