### ISSUE TITLE
No admin rights over this repo

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basiljs.github.io#3]
Due to the fact that I'm a member not an admin I have no admin rights over this repo. Dear admins can one of you please give this team https://github.com/orgs/basiljs/teams admin rights over this repo? Would be great.

**Comment by b-g** [comment]
Done the Docs team has admin rights for the doc repo now.
@ffd8 Just admins can setup web hooks etc.

**Comment by fabianmoronzirfas** [comment]
Thanks @b-g
