### ISSUE TITLE
Tutorials need description in HTML

### ISSUE THREAD

**Issue by ffd8** [basiljs/basiljs.github.io#35]
The tutorials overview are missing their short description under the title (as HTML to be stylized)

**Comment by fabianmoronzirfas** [comment]
Do you mean on this page?

![cleanshot 2018-09-16 at 21 30 01 2x](https://user-images.githubusercontent.com/315106/45600128-ce0fc200-b9f7-11e8-832e-f38bde37df5b.png)

@ffd8 There is no short description for the pages. Should I just take the first 50 words or so or do you want to add a description as meta datato the frontmatter of the tutorials?

**Comment by ffd8** [comment]
@fabianmoronzirfas Ah strange.. I wonder if it's a special field in the exported pages? I was imagining the [same short description](http://basiljs.ch/tutorials/) as on the present site would be available?
