### ISSUE TITLE
Develop branch reference browsable online?

### ISSUE THREAD

**Issue by ffd8** [basiljs/basiljs.github.io#40]
EDIT: Just created a default reference jsdoc – so a solution is found... although not as easy to browse as the category version...

@fabianmoronzirfas would it be possible to update the visible basiljs.github.io page with the latest b-less dev reference? Or, perhaps under a sub-dir? I've had some students using the develop branch, but there isn't yet an easy way to read the reference (edit- just used jsdoc) for new features that have been added. 

+ Seeing the default jsdoc output, there's some nice features the yuidoc didn't have, including the small 'opt' next to an optional input param and the output `→ {Number}`. We should consider adding this or stick with `Returns:` at the bottom?

**Comment by fabianmoronzirfas** [comment]
I think that we can merge dev into master. And have the latest state live on the GitHub pages. Makes it way easier to confirm if it really works. We can add a short notice to the starting page that this is still WIP and refers to the develop branch and v.2.0 of the project. @basiljs/basil-js-core-members any objections?

**Comment by fabianmoronzirfas** [comment]
Alternative version is --> https://basiljs2.netlify.com/
This is based on thedev branch. I'm not sure if it rebuilds on a merge into dev. We will see. I'll report back on this

**Comment by ffd8** [comment]
Thankyouverymuch for setting this up so fast!
+ fantastic if merges auto-rebuild...

**Comment by fabianmoronzirfas** [comment]
does rebuild. I close this issue
