### ISSUE TITLE
add gallery slider (or other pattern?)

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basiljs.github.io#51]
does gallery page have lytebox or slider?? (backend) – right now it's main image, text, code, then extra images/video.. should it be small w/ lytebox?

**Comment by fabianmoronzirfas** [comment]
https://github.com/pawelgrzybek/siema (discontinued)

https://glidejs.com

https://github.com/ganlanyuan/tiny-slider

https://github.com/metafizzy/flickity

**Comment by trych** [comment]
I think I would prefer to just have images simply all below each other without further interaction (so no slideshow). Find this simpler and also easier to navigate for the user.

**Comment by fabianmoronzirfas** [comment]
This comment on siema made me think "do we need a slider? or can we use a different type of overview?" 

> Two years later I consider carousels as an anti-pattern and I would suggest you to find a better UI pattern than carousel for your current project.

For my [gestalten-in-code](https://interface.fh-potsdam.de/gestalten-in-code/basiljs/) site I used a "card layout".
![interface fh-potsdam de_gestalten-in-code_basiljs_](https://user-images.githubusercontent.com/315106/54475089-aace9f80-47ed-11e9-857b-b202a3e80607.png)


Which could be randomised or have some sort or search features. Opinions? @trych @ffd8 @b-g ?

**Comment by fabianmoronzirfas** [comment]
> I think I would prefer to just have images simply all below each other without further interaction (so no slideshow). Find this simpler and also easier to navigate for the user.

Ha. Totally with you @trych . Didn't see this comment. while writing.

**Comment by b-g** [comment]
@fabianmoronzirfas @trych 

+1

> I think I would prefer to just have images simply all below each other without further interaction (so no slideshow). Find this simpler and also easier to navigate for the user.

I just would want to add to the images: Project Title (and maybe also in small: by Maxi Musterfrau)
