### ISSUE TITLE
check hilightjs initiation – not sure if this is on Kaj or you need to include some backend code?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basiljs.github.io#53]

**Comment by fabianmoronzirfas** [comment]
This issue is not related to some front or backend thing. @ffd8 you must use the definition for a syntax when adding a codeblock.

In the tutorials there is only


    ```
    some code
    ```

It should be

    ```js
    some code
    ```

I fixed this for one of the tutorials but don't have the time to do this now. Maybe later. If you beat me to it first… :-)

**Comment by fabianmoronzirfas** [comment]
BTW I also used ` ```java` for the processing vs basil examples. Gives a better highlighting

**Comment by ffd8** [comment]
Aha good to know, sure, will go through and correct all of those... *woooohoooo*
