### ISSUE TITLE
object properties display

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basiljs.github.io#6]
the display of object properties is currently wrong. Objects.properties should not get append to the function string

**Comment by fabianmoronzirfas** [comment]
This is where the problem is located https://github.com/basiljs/basiljs.github.io/blob/master/.bin/lib/data-generator.js#L13

**Comment by fabianmoronzirfas** [comment]
f94845e496d1baba6304f33789edc79beb7dc595 closes this issue

**Comment by trych** [comment]
Awesome!
You have no idea how great it is to teach a basil workshop and _while_ you are teaching it, the docs are gradually improved over the day, haha. 😄

**Comment by fabianmoronzirfas** [comment]
😎
